### ISSUE TITLE
Un message d'erreur est affiché lors de la saisie d'une valeur non numérique pour $_POST['value']

### ISSUE THREAD

**Issue by matthieuaudemard** [gillout/calculator#1]
Un message d'erreur est affiché lors de l'envoi d'un caractère non numérique pour l'attribue value (c.f : P.J). 
Il est préférable d'afficher un message d'erreur "contrôlé" dans le champs input de la vue à l'aide de la méthode AppController::error.

![ano 1](https://user-images.githubusercontent.com/4210719/79228439-b6adea80-7e61-11ea-8fae-2d50de08ccf4.png)

**Comment by gtaigniere** [comment]
Au niveau de la classe Calculator, une exception était levée mais pas attrapée, lors de l'entrée d'une valeur non numérique.
