### ISSUE TITLE
Après avoir saisi des valeurs, la page n'affiche plus les valeurs saisies.

### ISSUE THREAD

**Issue by matthieuaudemard** [gillout/calculator#2]
- Saisir une valeur sur la calculatrice (un ou plusieurs chiffres)
- Réafficher la page en validant l'adresse dans la barre d'adresse
Voilà le résultat obtenu :

![Screenshot_2020-04-14 calculator](https://user-images.githubusercontent.com/4210719/79229056-b6621f00-7e62-11ea-9dee-4835e5b22c89.png)

**Comment by gtaigniere** [comment]
Dans le contrôleur, lors de l'affichage de l'index, le contenu de l'accumulateur ainsi que celui des inputs n'étaient pas pris en compte.
